language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - python -m ipykernel install --user --name travis_env --display-name "Python (travis_env)"


script:
  - nosetests --with-coverage

after_success:
  - coveralls
