language: python
python:
  - "3.5"

services:
  - docker

before_install:
  - pip install coveralls
  - cd src
  - docker build -t deepscent_test:latest . 

script:
  - docker run --volume $(pwd)/docker_volume:/notebooks/output --env COVERAGE_FILE=/notebooks/output/.coverage --env TRAVIS_JOB_ID="$TRAVIS_JOB_ID" --env TRAVIS_BRANCH="$TRAVIS_BRANCH" deepscent_test:latest
  - cp docker_volume/.coverage ./.coverage
  - ls -al
after_success:
  coveralls