language: python
python:
  - "3.5"

services:
  - docker

before_install:
  - pip install coveralls
  - cd src
  - docker build -t deepscent_test:latest . 

script:
  - coverage erase
  - docker run --env TRAVIS_JOB_ID="$TRAVIS_JOB_ID" --env TRAVIS_BRANCH="$TRAVIS_BRANCH" --name deepscent_container deepscent_test:latest
  - docker cp deepscent_container:notebooks/src/.coverage ./.coverage

after_success:
  - coverage combine --rcfile=.coveragerc .coverage
  - coveralls