language: python
python:
  - "3.5"

services:
  - docker

before_install:
  - pip install coveralls
  - cd src
  - docker build -t deepscent_test:latest . 

script:
  - docker run --volume $(pwd)/docker_volume:/notebooks/output -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" deepscent_test:latest

after_success:
  coveralls