language: python
python:
  - "3.5"

services:
  - docker

before_install:
  - pip install coveralls
  - cd src
  - docker build -t deepscent_test:latest . 

script:
  - docker run --env TRAVIS_JOB_ID="$TRAVIS_JOB_ID" --env TRAVIS_BRANCH="$TRAVIS_BRANCH" deepscent_test:latest
  - docker cp deepscent_test:notebooks/src/.coverage ./.coverage
  - ls -al
after_success:
  - coverage combine
  - coveralls