FROM tensorflow/tensorflow:1.13.1-gpu-py3-jupyter
RUN pip install requests==2.22.0
RUN pip install matplotlib==3.0.2
RUN pip install pandas==0.24.1
RUN pip install scikit-learn==0.20.2
RUN pip install ruptures==1.0.1
RUN pip install seaborn==0.9.0

